# This file was generated by GoReleaser. DO NOT EDIT.
cask "gorched" do
  desc "Terminal based game inspired by \"The Mother of all games\" Scorched Earth"
  homepage "https://github.com/zladovan/gorched"
  version "1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gorched"

  on_macos do
    on_intel do
      url "https://github.com/zladovan/gorched/releases/download/v1.7/gorched_1.7_darwin_amd64.tar.gz"
      sha256 "f8fcb7d5310371fedd7037e86d107b19294278c0ba20978216d7d908c9f92ba4"
    end
    on_arm do
      url "https://github.com/zladovan/gorched/releases/download/v1.7/gorched_1.7_darwin_arm64.tar.gz"
      sha256 "059228809782a9d59723418daf6a8282b8ba7fe9ab521992878c1309009d48c0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zladovan/gorched/releases/download/v1.7/gorched_1.7_linux_amd64.tar.gz"
      sha256 "fe23f42cee8b2b51a038b0524c770d88323bf77237db1e45881ce36f403550b0"
    end
    on_arm do
      url "https://github.com/zladovan/gorched/releases/download/v1.7/gorched_1.7_linux_arm64.tar.gz"
      sha256 "344182c26f81ec8d0528b4a4c0c184e5353ef51396b61b13251ddce107df9e2b"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'foo' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
    end
  end

  # No zap stanza required
end
