# This file was generated by GoReleaser. DO NOT EDIT.
class Gorched < Formula
  desc "Terminal based game inspired by \"The Mother of all games\" Scorched Earth"
  homepage "https://github.com/zladovan/gorched"
  version "1.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zladovan/gorched/releases/download/v1.5/gorched_1.5_Darwin_x86_64.tar.gz"
    sha256 "35a639fa0501497151d168fdd438040d53539334ee4672790a67620b9bf8a15d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/zladovan/gorched/releases/download/v1.5/gorched_1.5_Linux_x86_64.tar.gz"
      sha256 "aa7935f449cadc735bd3e2530fb248c31a778c4b6d94484b98a1797dc636505b"
    end
  end

  def install
    bin.install "gorched"
  end
end
